
-- Criando a tabela Pais --
CREATE TABLE Pais(
PaisID INT NOT NULL IDENTITY (1,1),
Nome VARCHAR(MAX) NOT NULL,
Sigla CHAR(2) NOT NULL,
DataInsert DATETIME NULL DEFAULT GETDATE(),
CONSTRAINT PK_PaisID PRIMARY KEY (PaisID)
)
GO

-- Criando a tabela Departamento --
CREATE TABLE Departamento(
DepID INT NOT NULL IDENTITY (1,1),
Nome VARCHAR(MAX) NOT NULL,
DataInsert DATETIME NULL DEFAULT GETDATE(),
CONSTRAINT PK_DepID PRIMARY KEY (DepID)
)
GO

-- Criando a tabela Funcionario --
CREATE TABLE Funcionario(
FuncionarioID INT NOT NULL,
Chave BIGINT NOT NULL,
Nome VARCHAR(MAX) NOT NULL,
Sobrenome VARCHAR(MAX) NOT NULL,
Sexo CHAR(1) NOT NULL,
DataNascimento DATETIME NOT NULL,
Email VARCHAR(MAX) NOT NULL,
PaisID INT NOT NULL,
DataAdmissao DATETIME NOT NULL,
DataInsert DATETIME NULL DEFAULT GETDATE(),
Ctps VARCHAR(50) NOT NULL,
CtpsNum BIGINT NOT NULL,
CtpSerie BIGINT NOT NULL, 
CONSTRAINT PK_FuncionarioID PRIMARY KEY (FuncionarioID)
)
GO
